cluster:
  name: my-rke2-cluster
  version: v1.32.3
  airgap_bundle_path: /opt/rke2-airgap-bundle.tar.gz # Note Store this on the machine you're running this tool from
  rke2_rpm_path: /opt/rke2/rpms
  tar_extract_path: /opt/rke2
  systemd_service_path: /etc/systemd/system/ # Not using as of now

  # Config yaml settings
  domain: example.com # Define a domain for your cluster
  token: K1078d6efc5ece52ed16e86a6d19bddfb222e89862efc74b7f9187f203fbc06fa00::server:a3dab4acb8829dedba9b7fe99966c153
  cluster_cidr: 10.42.0.0/16
  service_cidr: 10.43.0.0/16
  cni:
    - multus
    - canal
  disable_network_policy: false
  write_kubeconfig_mode: "0644"
  kube_apiserver_arg:
    - "enable-admission-plugins=NodeRestriction,PodSecurityPolicy"
  container_runtime_endpoint: unix:///var/run/k3s/containerd/containerd.sock
  pause_image: registry.example.com/pause:3.6
  disable:
    - rke2-ingress-nginx

nodes:
  servers:
    - hostname: rke2-server-1
      ip: 10.0.4.10
      user: root
      ssh_key: .ssh/rke2_cluster_key

    # - hostname: rke2-server-2
    #   ip: 192.168.1.11
    #   user: root
    #   ssh_key: /path/to/private_key

  agents:
    - hostname: rke2-agent-1
      ip: 10.0.4.177
      user: root
      ssh_key: .ssh/rke2_cluster_key
    # - hostname: rke2-agent-2
    #   ip: 192.168.1.21
    #   user: root
    #   ssh_key: /path/to/private_key
